# Generated by Django 4.2.6 on 2023-10-20 12:53

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('anketa', '0004_alter_answers_options_delete_metest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grajdanin',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.FileField(upload_to='', verbose_name='Аватар')),
                ('number', models.TextField(verbose_name='Номер телефона')),
                ('birthday', models.DateField(verbose_name='Дата рождения')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['-username'],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Users_certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.IntegerField(verbose_name='Сертификат')),
                ('main_skill', models.TextField(verbose_name='Основной навык')),
                ('all_skills', models.TextField(verbose_name='Все навыки')),
                ('date_of_text', models.DateField(verbose_name='Дата')),
                ('my_full_certificate', models.FileField(upload_to='', verbose_name='Мой полный сертификат')),
                ('my_one_certificate', models.FileField(upload_to='', verbose_name='Мой одиночный сертификат')),
                ('grajdanin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='testik.grajdanin', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-grajdanin'],
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_points', models.IntegerField(verbose_name='Количество очков')),
                ('date', models.DateField(verbose_name='Дата прохождения')),
                ('professia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='professiaanswers', to='anketa.professia', verbose_name='Профессия')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='skillanswers', to='anketa.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['-professia'],
            },
        ),
    ]
