# Generated by Django 4.2.6 on 2023-10-20 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Профессия',
                'verbose_name_plural': 'Профессии',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.TextField(max_length=50, verbose_name='Название')),
                ('point', models.IntegerField(verbose_name='Очки')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-text_question'],
            },
        ),
        migrations.CreateModel(
            name='MeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
                ('professia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.professia', verbose_name='Профессия')),
            ],
            options={
                'verbose_name': 'Мой новый класс',
                'verbose_name_plural': 'Мой новый класс',
                'ordering': ['-title'],
            },
        ),
    ]
