# Generated by Django 4.2.6 on 2023-10-20 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_points', models.TextField(max_length=50, verbose_name='Количество очков')),
                ('professia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.professia', verbose_name='Профессия')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Модель профессии',
                'verbose_name_plural': 'Модели профессий',
                'ordering': ['-number_of_points'],
            },
        ),
    ]
