# Generated by Django 4.2.6 on 2023-10-20 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0002_model_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empty_certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.TextField(max_length=200, verbose_name='Сертификат')),
                ('full_file', models.FileField(upload_to='', verbose_name='Все файлы')),
                ('one_file', models.FileField(upload_to='', verbose_name='Один файл')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-certificate'],
            },
        ),
        migrations.AlterModelOptions(
            name='model_profession',
            options={'ordering': ['-professia'], 'verbose_name': 'Модель профессии', 'verbose_name_plural': 'Модели профессий'},
        ),
        migrations.AlterField(
            model_name='model_profession',
            name='number_of_points',
            field=models.IntegerField(verbose_name='Количество очков'),
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_points', models.IntegerField(verbose_name='Количество очков')),
                ('date', models.DateField(verbose_name='Дата прохождения')),
                ('professia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.professia', verbose_name='Профессия')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.skill', verbose_name='Навык')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['professia'],
            },
        ),
    ]
