# Generated by Django 4.2.6 on 2023-10-20 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anketa', '0003_empty_certificate_alter_model_profession_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answers',
            options={'ordering': ['-professia'], 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.DeleteModel(
            name='MeTest',
        ),
    ]
